### ISSUE TITLE
第一次暂停需要点击两次才能暂停。

### ISSUE THREAD

**Issue by xingzhixin** [cyrilis/Douban-FM-Express#1]
Package/javascripts/main.js

第60行~67行，if..else内代码对调一下即可解决。

能做出小小贡献，我很开心~~~

**Comment by cyrilis** [comment]
@xingzhixin  
Thank you ! 

确实是这样. :+1: 
我近期可能会更新新版本, 尽量年前完成. 因为现在的 js 结构我都怀疑是不是我自己写的.... 
后期会加上频道切换等.

Thanks for your contribution !

**Comment by cyrilis** [comment]
Close due to new implementation applied.
